### ISSUE TITLE
I see a lot of panic()

### ISSUE THREAD

**Issue by guettli** [jrhouston/k8slock#7]
First I thought: Great, a nice library which helps me to sync two controllers.

Then I looked at the code and see many `panic()` calls.

Just out of curiosity, why do you use panic() so often?

**Comment by jrhouston** [comment]
Yeah I don't like this either. It's because this library is implementing the [Locker](https://pkg.go.dev/sync#Locker) interface which doesn't return `error` so you have to produce a panic if something goes wrong.

**Comment by jrhouston** [comment]
If you wanted to add new functions that supported error + context to go alongside the locker interface I'd be open to adding that, i.e:

```
LockContext(context.Context) error
UnlockContext(context.Context) error
```

**Comment by guettli** [comment]
I personally don't care about the Locker interface. I was looking for a way to sync two replicas of a kubernetes controller.

Someone pointed me to this method, and I wanted to avoid copy+paste and looked for an alternative.

https://github.com/kubernetes-sigs/cluster-api/blob/f2ba999757aa76b446943a9ffea14ecf8c7523e8/bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go#L51
